version: '3'

services:
  database:
    image: mongo:4.4
    container_name: mongo44
    ports:
      - "27017:27017"
    restart: always
    networks:
      lineMongo-proxy:
        ipv4_address: 172.20.0.101
  line_mongo:
    build:
      context: ../
      dockerfile: ./deployments/Dockerfile
    image: line_mongo
    container_name: line_mongo
    ports:
      - "8080:8080"
    networks:
      lineMongo-proxy:
        ipv4_address: 172.20.0.102

networks:
  lineMongo-proxy:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24

